// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dungeon.proto
// Protobuf C++ Version: 5.29.5

#ifndef dungeon_2eproto_2epb_2eh
#define dungeon_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "common.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_dungeon_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_dungeon_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_dungeon_2eproto;
namespace murim {
class DungeonActionRequest;
struct DungeonActionRequestDefaultTypeInternal;
extern DungeonActionRequestDefaultTypeInternal _DungeonActionRequest_default_instance_;
class DungeonReward;
struct DungeonRewardDefaultTypeInternal;
extern DungeonRewardDefaultTypeInternal _DungeonReward_default_instance_;
class DungeonStatusNotification;
struct DungeonStatusNotificationDefaultTypeInternal;
extern DungeonStatusNotificationDefaultTypeInternal _DungeonStatusNotification_default_instance_;
class EnterDungeonRequest;
struct EnterDungeonRequestDefaultTypeInternal;
extern EnterDungeonRequestDefaultTypeInternal _EnterDungeonRequest_default_instance_;
class EnterDungeonResponse;
struct EnterDungeonResponseDefaultTypeInternal;
extern EnterDungeonResponseDefaultTypeInternal _EnterDungeonResponse_default_instance_;
class LeaveDungeonRequest;
struct LeaveDungeonRequestDefaultTypeInternal;
extern LeaveDungeonRequestDefaultTypeInternal _LeaveDungeonRequest_default_instance_;
}  // namespace murim
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace murim {
enum DungeonType : int {
  SINGLE = 0,
  TEAM = 1,
  RAID = 2,
  ARENA = 3,
  DungeonType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  DungeonType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool DungeonType_IsValid(int value);
extern const uint32_t DungeonType_internal_data_[];
constexpr DungeonType DungeonType_MIN = static_cast<DungeonType>(0);
constexpr DungeonType DungeonType_MAX = static_cast<DungeonType>(3);
constexpr int DungeonType_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor*
DungeonType_descriptor();
template <typename T>
const std::string& DungeonType_Name(T value) {
  static_assert(std::is_same<T, DungeonType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to DungeonType_Name().");
  return DungeonType_Name(static_cast<DungeonType>(value));
}
template <>
inline const std::string& DungeonType_Name(DungeonType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<DungeonType_descriptor,
                                                 0, 3>(
      static_cast<int>(value));
}
inline bool DungeonType_Parse(absl::string_view name, DungeonType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DungeonType>(
      DungeonType_descriptor(), name, value);
}
enum DungeonDifficulty : int {
  DUNGEON_EASY = 0,
  DUNGEON_NORMAL = 1,
  DUNGEON_HARD = 2,
  DUNGEON_EXPERT = 3,
  DungeonDifficulty_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  DungeonDifficulty_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool DungeonDifficulty_IsValid(int value);
extern const uint32_t DungeonDifficulty_internal_data_[];
constexpr DungeonDifficulty DungeonDifficulty_MIN = static_cast<DungeonDifficulty>(0);
constexpr DungeonDifficulty DungeonDifficulty_MAX = static_cast<DungeonDifficulty>(3);
constexpr int DungeonDifficulty_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor*
DungeonDifficulty_descriptor();
template <typename T>
const std::string& DungeonDifficulty_Name(T value) {
  static_assert(std::is_same<T, DungeonDifficulty>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to DungeonDifficulty_Name().");
  return DungeonDifficulty_Name(static_cast<DungeonDifficulty>(value));
}
template <>
inline const std::string& DungeonDifficulty_Name(DungeonDifficulty value) {
  return ::google::protobuf::internal::NameOfDenseEnum<DungeonDifficulty_descriptor,
                                                 0, 3>(
      static_cast<int>(value));
}
inline bool DungeonDifficulty_Parse(absl::string_view name, DungeonDifficulty* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DungeonDifficulty>(
      DungeonDifficulty_descriptor(), name, value);
}
enum DungeonStatus : int {
  DUNGEON_NOT_STARTED = 0,
  DUNGEON_IN_PROGRESS = 1,
  DUNGEON_COMPLETED = 2,
  DUNGEON_FAILED = 3,
  DungeonStatus_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  DungeonStatus_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool DungeonStatus_IsValid(int value);
extern const uint32_t DungeonStatus_internal_data_[];
constexpr DungeonStatus DungeonStatus_MIN = static_cast<DungeonStatus>(0);
constexpr DungeonStatus DungeonStatus_MAX = static_cast<DungeonStatus>(3);
constexpr int DungeonStatus_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor*
DungeonStatus_descriptor();
template <typename T>
const std::string& DungeonStatus_Name(T value) {
  static_assert(std::is_same<T, DungeonStatus>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to DungeonStatus_Name().");
  return DungeonStatus_Name(static_cast<DungeonStatus>(value));
}
template <>
inline const std::string& DungeonStatus_Name(DungeonStatus value) {
  return ::google::protobuf::internal::NameOfDenseEnum<DungeonStatus_descriptor,
                                                 0, 3>(
      static_cast<int>(value));
}
inline bool DungeonStatus_Parse(absl::string_view name, DungeonStatus* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DungeonStatus>(
      DungeonStatus_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class LeaveDungeonRequest final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:murim.LeaveDungeonRequest) */ {
 public:
  inline LeaveDungeonRequest() : LeaveDungeonRequest(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(LeaveDungeonRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(LeaveDungeonRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR LeaveDungeonRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline LeaveDungeonRequest(const LeaveDungeonRequest& from) : LeaveDungeonRequest(nullptr, from) {}
  inline LeaveDungeonRequest(LeaveDungeonRequest&& from) noexcept
      : LeaveDungeonRequest(nullptr, std::move(from)) {}
  inline LeaveDungeonRequest& operator=(const LeaveDungeonRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline LeaveDungeonRequest& operator=(LeaveDungeonRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LeaveDungeonRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const LeaveDungeonRequest* internal_default_instance() {
    return reinterpret_cast<const LeaveDungeonRequest*>(
        &_LeaveDungeonRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(LeaveDungeonRequest& a, LeaveDungeonRequest& b) { a.Swap(&b); }
  inline void Swap(LeaveDungeonRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LeaveDungeonRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LeaveDungeonRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<LeaveDungeonRequest>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const LeaveDungeonRequest& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const LeaveDungeonRequest& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "murim.LeaveDungeonRequest"; }

 protected:
  explicit LeaveDungeonRequest(::google::protobuf::Arena* arena);
  LeaveDungeonRequest(::google::protobuf::Arena* arena, const LeaveDungeonRequest& from);
  LeaveDungeonRequest(::google::protobuf::Arena* arena, LeaveDungeonRequest&& from) noexcept
      : LeaveDungeonRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:murim.LeaveDungeonRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 0, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const LeaveDungeonRequest& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_dungeon_2eproto;
};
// -------------------------------------------------------------------

class EnterDungeonRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:murim.EnterDungeonRequest) */ {
 public:
  inline EnterDungeonRequest() : EnterDungeonRequest(nullptr) {}
  ~EnterDungeonRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(EnterDungeonRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(EnterDungeonRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR EnterDungeonRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline EnterDungeonRequest(const EnterDungeonRequest& from) : EnterDungeonRequest(nullptr, from) {}
  inline EnterDungeonRequest(EnterDungeonRequest&& from) noexcept
      : EnterDungeonRequest(nullptr, std::move(from)) {}
  inline EnterDungeonRequest& operator=(const EnterDungeonRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline EnterDungeonRequest& operator=(EnterDungeonRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EnterDungeonRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const EnterDungeonRequest* internal_default_instance() {
    return reinterpret_cast<const EnterDungeonRequest*>(
        &_EnterDungeonRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(EnterDungeonRequest& a, EnterDungeonRequest& b) { a.Swap(&b); }
  inline void Swap(EnterDungeonRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EnterDungeonRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EnterDungeonRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<EnterDungeonRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const EnterDungeonRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const EnterDungeonRequest& from) { EnterDungeonRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(EnterDungeonRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "murim.EnterDungeonRequest"; }

 protected:
  explicit EnterDungeonRequest(::google::protobuf::Arena* arena);
  EnterDungeonRequest(::google::protobuf::Arena* arena, const EnterDungeonRequest& from);
  EnterDungeonRequest(::google::protobuf::Arena* arena, EnterDungeonRequest&& from) noexcept
      : EnterDungeonRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDungeonIdFieldNumber = 1,
    kDifficultyFieldNumber = 2,
  };
  // uint32 dungeon_id = 1;
  void clear_dungeon_id() ;
  ::uint32_t dungeon_id() const;
  void set_dungeon_id(::uint32_t value);

  private:
  ::uint32_t _internal_dungeon_id() const;
  void _internal_set_dungeon_id(::uint32_t value);

  public:
  // uint32 difficulty = 2;
  void clear_difficulty() ;
  ::uint32_t difficulty() const;
  void set_difficulty(::uint32_t value);

  private:
  ::uint32_t _internal_difficulty() const;
  void _internal_set_difficulty(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:murim.EnterDungeonRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const EnterDungeonRequest& from_msg);
    ::uint32_t dungeon_id_;
    ::uint32_t difficulty_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_dungeon_2eproto;
};
// -------------------------------------------------------------------

class DungeonStatusNotification final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:murim.DungeonStatusNotification) */ {
 public:
  inline DungeonStatusNotification() : DungeonStatusNotification(nullptr) {}
  ~DungeonStatusNotification() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(DungeonStatusNotification* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(DungeonStatusNotification));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DungeonStatusNotification(
      ::google::protobuf::internal::ConstantInitialized);

  inline DungeonStatusNotification(const DungeonStatusNotification& from) : DungeonStatusNotification(nullptr, from) {}
  inline DungeonStatusNotification(DungeonStatusNotification&& from) noexcept
      : DungeonStatusNotification(nullptr, std::move(from)) {}
  inline DungeonStatusNotification& operator=(const DungeonStatusNotification& from) {
    CopyFrom(from);
    return *this;
  }
  inline DungeonStatusNotification& operator=(DungeonStatusNotification&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DungeonStatusNotification& default_instance() {
    return *internal_default_instance();
  }
  static inline const DungeonStatusNotification* internal_default_instance() {
    return reinterpret_cast<const DungeonStatusNotification*>(
        &_DungeonStatusNotification_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(DungeonStatusNotification& a, DungeonStatusNotification& b) { a.Swap(&b); }
  inline void Swap(DungeonStatusNotification* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DungeonStatusNotification* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DungeonStatusNotification* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<DungeonStatusNotification>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DungeonStatusNotification& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DungeonStatusNotification& from) { DungeonStatusNotification::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(DungeonStatusNotification* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "murim.DungeonStatusNotification"; }

 protected:
  explicit DungeonStatusNotification(::google::protobuf::Arena* arena);
  DungeonStatusNotification(::google::protobuf::Arena* arena, const DungeonStatusNotification& from);
  DungeonStatusNotification(::google::protobuf::Arena* arena, DungeonStatusNotification&& from) noexcept
      : DungeonStatusNotification(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDungeonIdFieldNumber = 1,
    kStatusFieldNumber = 2,
  };
  // uint32 dungeon_id = 1;
  void clear_dungeon_id() ;
  ::uint32_t dungeon_id() const;
  void set_dungeon_id(::uint32_t value);

  private:
  ::uint32_t _internal_dungeon_id() const;
  void _internal_set_dungeon_id(::uint32_t value);

  public:
  // .murim.DungeonStatus status = 2;
  void clear_status() ;
  ::murim::DungeonStatus status() const;
  void set_status(::murim::DungeonStatus value);

  private:
  ::murim::DungeonStatus _internal_status() const;
  void _internal_set_status(::murim::DungeonStatus value);

  public:
  // @@protoc_insertion_point(class_scope:murim.DungeonStatusNotification)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const DungeonStatusNotification& from_msg);
    ::uint32_t dungeon_id_;
    int status_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_dungeon_2eproto;
};
// -------------------------------------------------------------------

class DungeonReward final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:murim.DungeonReward) */ {
 public:
  inline DungeonReward() : DungeonReward(nullptr) {}
  ~DungeonReward() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(DungeonReward* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(DungeonReward));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DungeonReward(
      ::google::protobuf::internal::ConstantInitialized);

  inline DungeonReward(const DungeonReward& from) : DungeonReward(nullptr, from) {}
  inline DungeonReward(DungeonReward&& from) noexcept
      : DungeonReward(nullptr, std::move(from)) {}
  inline DungeonReward& operator=(const DungeonReward& from) {
    CopyFrom(from);
    return *this;
  }
  inline DungeonReward& operator=(DungeonReward&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DungeonReward& default_instance() {
    return *internal_default_instance();
  }
  static inline const DungeonReward* internal_default_instance() {
    return reinterpret_cast<const DungeonReward*>(
        &_DungeonReward_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(DungeonReward& a, DungeonReward& b) { a.Swap(&b); }
  inline void Swap(DungeonReward* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DungeonReward* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DungeonReward* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<DungeonReward>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DungeonReward& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DungeonReward& from) { DungeonReward::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(DungeonReward* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "murim.DungeonReward"; }

 protected:
  explicit DungeonReward(::google::protobuf::Arena* arena);
  DungeonReward(::google::protobuf::Arena* arena, const DungeonReward& from);
  DungeonReward(::google::protobuf::Arena* arena, DungeonReward&& from) noexcept
      : DungeonReward(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kItemIdFieldNumber = 1,
    kCountFieldNumber = 2,
    kExpFieldNumber = 3,
    kGoldFieldNumber = 4,
  };
  // uint32 item_id = 1;
  void clear_item_id() ;
  ::uint32_t item_id() const;
  void set_item_id(::uint32_t value);

  private:
  ::uint32_t _internal_item_id() const;
  void _internal_set_item_id(::uint32_t value);

  public:
  // uint32 count = 2;
  void clear_count() ;
  ::uint32_t count() const;
  void set_count(::uint32_t value);

  private:
  ::uint32_t _internal_count() const;
  void _internal_set_count(::uint32_t value);

  public:
  // uint32 exp = 3;
  void clear_exp() ;
  ::uint32_t exp() const;
  void set_exp(::uint32_t value);

  private:
  ::uint32_t _internal_exp() const;
  void _internal_set_exp(::uint32_t value);

  public:
  // uint32 gold = 4;
  void clear_gold() ;
  ::uint32_t gold() const;
  void set_gold(::uint32_t value);

  private:
  ::uint32_t _internal_gold() const;
  void _internal_set_gold(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:murim.DungeonReward)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const DungeonReward& from_msg);
    ::uint32_t item_id_;
    ::uint32_t count_;
    ::uint32_t exp_;
    ::uint32_t gold_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_dungeon_2eproto;
};
// -------------------------------------------------------------------

class DungeonActionRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:murim.DungeonActionRequest) */ {
 public:
  inline DungeonActionRequest() : DungeonActionRequest(nullptr) {}
  ~DungeonActionRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(DungeonActionRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(DungeonActionRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DungeonActionRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline DungeonActionRequest(const DungeonActionRequest& from) : DungeonActionRequest(nullptr, from) {}
  inline DungeonActionRequest(DungeonActionRequest&& from) noexcept
      : DungeonActionRequest(nullptr, std::move(from)) {}
  inline DungeonActionRequest& operator=(const DungeonActionRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline DungeonActionRequest& operator=(DungeonActionRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DungeonActionRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const DungeonActionRequest* internal_default_instance() {
    return reinterpret_cast<const DungeonActionRequest*>(
        &_DungeonActionRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(DungeonActionRequest& a, DungeonActionRequest& b) { a.Swap(&b); }
  inline void Swap(DungeonActionRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DungeonActionRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DungeonActionRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<DungeonActionRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DungeonActionRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DungeonActionRequest& from) { DungeonActionRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(DungeonActionRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "murim.DungeonActionRequest"; }

 protected:
  explicit DungeonActionRequest(::google::protobuf::Arena* arena);
  DungeonActionRequest(::google::protobuf::Arena* arena, const DungeonActionRequest& from);
  DungeonActionRequest(::google::protobuf::Arena* arena, DungeonActionRequest&& from) noexcept
      : DungeonActionRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kActionFieldNumber = 2,
    kDungeonIdFieldNumber = 1,
  };
  // string action = 2;
  void clear_action() ;
  const std::string& action() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_action(Arg_&& arg, Args_... args);
  std::string* mutable_action();
  PROTOBUF_NODISCARD std::string* release_action();
  void set_allocated_action(std::string* value);

  private:
  const std::string& _internal_action() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_action(
      const std::string& value);
  std::string* _internal_mutable_action();

  public:
  // uint32 dungeon_id = 1;
  void clear_dungeon_id() ;
  ::uint32_t dungeon_id() const;
  void set_dungeon_id(::uint32_t value);

  private:
  ::uint32_t _internal_dungeon_id() const;
  void _internal_set_dungeon_id(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:murim.DungeonActionRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      41, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const DungeonActionRequest& from_msg);
    ::google::protobuf::internal::ArenaStringPtr action_;
    ::uint32_t dungeon_id_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_dungeon_2eproto;
};
// -------------------------------------------------------------------

class EnterDungeonResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:murim.EnterDungeonResponse) */ {
 public:
  inline EnterDungeonResponse() : EnterDungeonResponse(nullptr) {}
  ~EnterDungeonResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(EnterDungeonResponse* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(EnterDungeonResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR EnterDungeonResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline EnterDungeonResponse(const EnterDungeonResponse& from) : EnterDungeonResponse(nullptr, from) {}
  inline EnterDungeonResponse(EnterDungeonResponse&& from) noexcept
      : EnterDungeonResponse(nullptr, std::move(from)) {}
  inline EnterDungeonResponse& operator=(const EnterDungeonResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline EnterDungeonResponse& operator=(EnterDungeonResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EnterDungeonResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const EnterDungeonResponse* internal_default_instance() {
    return reinterpret_cast<const EnterDungeonResponse*>(
        &_EnterDungeonResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(EnterDungeonResponse& a, EnterDungeonResponse& b) { a.Swap(&b); }
  inline void Swap(EnterDungeonResponse* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EnterDungeonResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EnterDungeonResponse* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<EnterDungeonResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const EnterDungeonResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const EnterDungeonResponse& from) { EnterDungeonResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(EnterDungeonResponse* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "murim.EnterDungeonResponse"; }

 protected:
  explicit EnterDungeonResponse(::google::protobuf::Arena* arena);
  EnterDungeonResponse(::google::protobuf::Arena* arena, const EnterDungeonResponse& from);
  EnterDungeonResponse(::google::protobuf::Arena* arena, EnterDungeonResponse&& from) noexcept
      : EnterDungeonResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kResponseFieldNumber = 1,
    kDungeonIdFieldNumber = 2,
  };
  // .murim.Response response = 1;
  bool has_response() const;
  void clear_response() ;
  const ::murim::Response& response() const;
  PROTOBUF_NODISCARD ::murim::Response* release_response();
  ::murim::Response* mutable_response();
  void set_allocated_response(::murim::Response* value);
  void unsafe_arena_set_allocated_response(::murim::Response* value);
  ::murim::Response* unsafe_arena_release_response();

  private:
  const ::murim::Response& _internal_response() const;
  ::murim::Response* _internal_mutable_response();

  public:
  // uint32 dungeon_id = 2;
  void clear_dungeon_id() ;
  ::uint32_t dungeon_id() const;
  void set_dungeon_id(::uint32_t value);

  private:
  ::uint32_t _internal_dungeon_id() const;
  void _internal_set_dungeon_id(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:murim.EnterDungeonResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const EnterDungeonResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::murim::Response* response_;
    ::uint32_t dungeon_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_dungeon_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// EnterDungeonRequest

// uint32 dungeon_id = 1;
inline void EnterDungeonRequest::clear_dungeon_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dungeon_id_ = 0u;
}
inline ::uint32_t EnterDungeonRequest::dungeon_id() const {
  // @@protoc_insertion_point(field_get:murim.EnterDungeonRequest.dungeon_id)
  return _internal_dungeon_id();
}
inline void EnterDungeonRequest::set_dungeon_id(::uint32_t value) {
  _internal_set_dungeon_id(value);
  // @@protoc_insertion_point(field_set:murim.EnterDungeonRequest.dungeon_id)
}
inline ::uint32_t EnterDungeonRequest::_internal_dungeon_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dungeon_id_;
}
inline void EnterDungeonRequest::_internal_set_dungeon_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dungeon_id_ = value;
}

// uint32 difficulty = 2;
inline void EnterDungeonRequest::clear_difficulty() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.difficulty_ = 0u;
}
inline ::uint32_t EnterDungeonRequest::difficulty() const {
  // @@protoc_insertion_point(field_get:murim.EnterDungeonRequest.difficulty)
  return _internal_difficulty();
}
inline void EnterDungeonRequest::set_difficulty(::uint32_t value) {
  _internal_set_difficulty(value);
  // @@protoc_insertion_point(field_set:murim.EnterDungeonRequest.difficulty)
}
inline ::uint32_t EnterDungeonRequest::_internal_difficulty() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.difficulty_;
}
inline void EnterDungeonRequest::_internal_set_difficulty(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.difficulty_ = value;
}

// -------------------------------------------------------------------

// LeaveDungeonRequest

// -------------------------------------------------------------------

// DungeonActionRequest

// uint32 dungeon_id = 1;
inline void DungeonActionRequest::clear_dungeon_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dungeon_id_ = 0u;
}
inline ::uint32_t DungeonActionRequest::dungeon_id() const {
  // @@protoc_insertion_point(field_get:murim.DungeonActionRequest.dungeon_id)
  return _internal_dungeon_id();
}
inline void DungeonActionRequest::set_dungeon_id(::uint32_t value) {
  _internal_set_dungeon_id(value);
  // @@protoc_insertion_point(field_set:murim.DungeonActionRequest.dungeon_id)
}
inline ::uint32_t DungeonActionRequest::_internal_dungeon_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dungeon_id_;
}
inline void DungeonActionRequest::_internal_set_dungeon_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dungeon_id_ = value;
}

// string action = 2;
inline void DungeonActionRequest::clear_action() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.action_.ClearToEmpty();
}
inline const std::string& DungeonActionRequest::action() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:murim.DungeonActionRequest.action)
  return _internal_action();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void DungeonActionRequest::set_action(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.action_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:murim.DungeonActionRequest.action)
}
inline std::string* DungeonActionRequest::mutable_action() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_action();
  // @@protoc_insertion_point(field_mutable:murim.DungeonActionRequest.action)
  return _s;
}
inline const std::string& DungeonActionRequest::_internal_action() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.action_.Get();
}
inline void DungeonActionRequest::_internal_set_action(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.action_.Set(value, GetArena());
}
inline std::string* DungeonActionRequest::_internal_mutable_action() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.action_.Mutable( GetArena());
}
inline std::string* DungeonActionRequest::release_action() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:murim.DungeonActionRequest.action)
  return _impl_.action_.Release();
}
inline void DungeonActionRequest::set_allocated_action(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.action_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.action_.IsDefault()) {
    _impl_.action_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:murim.DungeonActionRequest.action)
}

// -------------------------------------------------------------------

// EnterDungeonResponse

// .murim.Response response = 1;
inline bool EnterDungeonResponse::has_response() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.response_ != nullptr);
  return value;
}
inline const ::murim::Response& EnterDungeonResponse::_internal_response() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::murim::Response* p = _impl_.response_;
  return p != nullptr ? *p : reinterpret_cast<const ::murim::Response&>(::murim::_Response_default_instance_);
}
inline const ::murim::Response& EnterDungeonResponse::response() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:murim.EnterDungeonResponse.response)
  return _internal_response();
}
inline void EnterDungeonResponse::unsafe_arena_set_allocated_response(::murim::Response* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.response_);
  }
  _impl_.response_ = reinterpret_cast<::murim::Response*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:murim.EnterDungeonResponse.response)
}
inline ::murim::Response* EnterDungeonResponse::release_response() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::murim::Response* released = _impl_.response_;
  _impl_.response_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::murim::Response* EnterDungeonResponse::unsafe_arena_release_response() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:murim.EnterDungeonResponse.response)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::murim::Response* temp = _impl_.response_;
  _impl_.response_ = nullptr;
  return temp;
}
inline ::murim::Response* EnterDungeonResponse::_internal_mutable_response() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.response_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::murim::Response>(GetArena());
    _impl_.response_ = reinterpret_cast<::murim::Response*>(p);
  }
  return _impl_.response_;
}
inline ::murim::Response* EnterDungeonResponse::mutable_response() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::murim::Response* _msg = _internal_mutable_response();
  // @@protoc_insertion_point(field_mutable:murim.EnterDungeonResponse.response)
  return _msg;
}
inline void EnterDungeonResponse::set_allocated_response(::murim::Response* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.response_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.response_ = reinterpret_cast<::murim::Response*>(value);
  // @@protoc_insertion_point(field_set_allocated:murim.EnterDungeonResponse.response)
}

// uint32 dungeon_id = 2;
inline void EnterDungeonResponse::clear_dungeon_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dungeon_id_ = 0u;
}
inline ::uint32_t EnterDungeonResponse::dungeon_id() const {
  // @@protoc_insertion_point(field_get:murim.EnterDungeonResponse.dungeon_id)
  return _internal_dungeon_id();
}
inline void EnterDungeonResponse::set_dungeon_id(::uint32_t value) {
  _internal_set_dungeon_id(value);
  // @@protoc_insertion_point(field_set:murim.EnterDungeonResponse.dungeon_id)
}
inline ::uint32_t EnterDungeonResponse::_internal_dungeon_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dungeon_id_;
}
inline void EnterDungeonResponse::_internal_set_dungeon_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dungeon_id_ = value;
}

// -------------------------------------------------------------------

// DungeonStatusNotification

// uint32 dungeon_id = 1;
inline void DungeonStatusNotification::clear_dungeon_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dungeon_id_ = 0u;
}
inline ::uint32_t DungeonStatusNotification::dungeon_id() const {
  // @@protoc_insertion_point(field_get:murim.DungeonStatusNotification.dungeon_id)
  return _internal_dungeon_id();
}
inline void DungeonStatusNotification::set_dungeon_id(::uint32_t value) {
  _internal_set_dungeon_id(value);
  // @@protoc_insertion_point(field_set:murim.DungeonStatusNotification.dungeon_id)
}
inline ::uint32_t DungeonStatusNotification::_internal_dungeon_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dungeon_id_;
}
inline void DungeonStatusNotification::_internal_set_dungeon_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dungeon_id_ = value;
}

// .murim.DungeonStatus status = 2;
inline void DungeonStatusNotification::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = 0;
}
inline ::murim::DungeonStatus DungeonStatusNotification::status() const {
  // @@protoc_insertion_point(field_get:murim.DungeonStatusNotification.status)
  return _internal_status();
}
inline void DungeonStatusNotification::set_status(::murim::DungeonStatus value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:murim.DungeonStatusNotification.status)
}
inline ::murim::DungeonStatus DungeonStatusNotification::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::murim::DungeonStatus>(_impl_.status_);
}
inline void DungeonStatusNotification::_internal_set_status(::murim::DungeonStatus value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = value;
}

// -------------------------------------------------------------------

// DungeonReward

// uint32 item_id = 1;
inline void DungeonReward::clear_item_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.item_id_ = 0u;
}
inline ::uint32_t DungeonReward::item_id() const {
  // @@protoc_insertion_point(field_get:murim.DungeonReward.item_id)
  return _internal_item_id();
}
inline void DungeonReward::set_item_id(::uint32_t value) {
  _internal_set_item_id(value);
  // @@protoc_insertion_point(field_set:murim.DungeonReward.item_id)
}
inline ::uint32_t DungeonReward::_internal_item_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.item_id_;
}
inline void DungeonReward::_internal_set_item_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.item_id_ = value;
}

// uint32 count = 2;
inline void DungeonReward::clear_count() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.count_ = 0u;
}
inline ::uint32_t DungeonReward::count() const {
  // @@protoc_insertion_point(field_get:murim.DungeonReward.count)
  return _internal_count();
}
inline void DungeonReward::set_count(::uint32_t value) {
  _internal_set_count(value);
  // @@protoc_insertion_point(field_set:murim.DungeonReward.count)
}
inline ::uint32_t DungeonReward::_internal_count() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.count_;
}
inline void DungeonReward::_internal_set_count(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.count_ = value;
}

// uint32 exp = 3;
inline void DungeonReward::clear_exp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.exp_ = 0u;
}
inline ::uint32_t DungeonReward::exp() const {
  // @@protoc_insertion_point(field_get:murim.DungeonReward.exp)
  return _internal_exp();
}
inline void DungeonReward::set_exp(::uint32_t value) {
  _internal_set_exp(value);
  // @@protoc_insertion_point(field_set:murim.DungeonReward.exp)
}
inline ::uint32_t DungeonReward::_internal_exp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.exp_;
}
inline void DungeonReward::_internal_set_exp(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.exp_ = value;
}

// uint32 gold = 4;
inline void DungeonReward::clear_gold() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gold_ = 0u;
}
inline ::uint32_t DungeonReward::gold() const {
  // @@protoc_insertion_point(field_get:murim.DungeonReward.gold)
  return _internal_gold();
}
inline void DungeonReward::set_gold(::uint32_t value) {
  _internal_set_gold(value);
  // @@protoc_insertion_point(field_set:murim.DungeonReward.gold)
}
inline ::uint32_t DungeonReward::_internal_gold() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gold_;
}
inline void DungeonReward::_internal_set_gold(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gold_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace murim


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::murim::DungeonType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::murim::DungeonType>() {
  return ::murim::DungeonType_descriptor();
}
template <>
struct is_proto_enum<::murim::DungeonDifficulty> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::murim::DungeonDifficulty>() {
  return ::murim::DungeonDifficulty_descriptor();
}
template <>
struct is_proto_enum<::murim::DungeonStatus> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::murim::DungeonStatus>() {
  return ::murim::DungeonStatus_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // dungeon_2eproto_2epb_2eh
