// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dungeon.proto
// Protobuf C++ Version: 5.29.5

#include "dungeon.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace murim {
              template <typename>
PROTOBUF_CONSTEXPR LeaveDungeonRequest::LeaveDungeonRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct LeaveDungeonRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LeaveDungeonRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LeaveDungeonRequestDefaultTypeInternal() {}
  union {
    LeaveDungeonRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LeaveDungeonRequestDefaultTypeInternal _LeaveDungeonRequest_default_instance_;

inline constexpr EnterDungeonRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : dungeon_id_{0u},
        difficulty_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR EnterDungeonRequest::EnterDungeonRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct EnterDungeonRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EnterDungeonRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EnterDungeonRequestDefaultTypeInternal() {}
  union {
    EnterDungeonRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EnterDungeonRequestDefaultTypeInternal _EnterDungeonRequest_default_instance_;

inline constexpr DungeonStatusNotification::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : dungeon_id_{0u},
        status_{static_cast< ::murim::DungeonStatus >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DungeonStatusNotification::DungeonStatusNotification(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DungeonStatusNotificationDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DungeonStatusNotificationDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DungeonStatusNotificationDefaultTypeInternal() {}
  union {
    DungeonStatusNotification _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DungeonStatusNotificationDefaultTypeInternal _DungeonStatusNotification_default_instance_;

inline constexpr DungeonReward::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : item_id_{0u},
        count_{0u},
        exp_{0u},
        gold_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DungeonReward::DungeonReward(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DungeonRewardDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DungeonRewardDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DungeonRewardDefaultTypeInternal() {}
  union {
    DungeonReward _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DungeonRewardDefaultTypeInternal _DungeonReward_default_instance_;

inline constexpr DungeonActionRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : action_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        dungeon_id_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DungeonActionRequest::DungeonActionRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DungeonActionRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DungeonActionRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DungeonActionRequestDefaultTypeInternal() {}
  union {
    DungeonActionRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DungeonActionRequestDefaultTypeInternal _DungeonActionRequest_default_instance_;

inline constexpr EnterDungeonResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        response_{nullptr},
        dungeon_id_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR EnterDungeonResponse::EnterDungeonResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct EnterDungeonResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EnterDungeonResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EnterDungeonResponseDefaultTypeInternal() {}
  union {
    EnterDungeonResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EnterDungeonResponseDefaultTypeInternal _EnterDungeonResponse_default_instance_;
}  // namespace murim
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_dungeon_2eproto[3];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_dungeon_2eproto = nullptr;
const ::uint32_t
    TableStruct_dungeon_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::murim::EnterDungeonRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::murim::EnterDungeonRequest, _impl_.dungeon_id_),
        PROTOBUF_FIELD_OFFSET(::murim::EnterDungeonRequest, _impl_.difficulty_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::murim::LeaveDungeonRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::murim::DungeonActionRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::murim::DungeonActionRequest, _impl_.dungeon_id_),
        PROTOBUF_FIELD_OFFSET(::murim::DungeonActionRequest, _impl_.action_),
        PROTOBUF_FIELD_OFFSET(::murim::EnterDungeonResponse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::murim::EnterDungeonResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::murim::EnterDungeonResponse, _impl_.response_),
        PROTOBUF_FIELD_OFFSET(::murim::EnterDungeonResponse, _impl_.dungeon_id_),
        0,
        ~0u,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::murim::DungeonStatusNotification, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::murim::DungeonStatusNotification, _impl_.dungeon_id_),
        PROTOBUF_FIELD_OFFSET(::murim::DungeonStatusNotification, _impl_.status_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::murim::DungeonReward, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::murim::DungeonReward, _impl_.item_id_),
        PROTOBUF_FIELD_OFFSET(::murim::DungeonReward, _impl_.count_),
        PROTOBUF_FIELD_OFFSET(::murim::DungeonReward, _impl_.exp_),
        PROTOBUF_FIELD_OFFSET(::murim::DungeonReward, _impl_.gold_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::murim::EnterDungeonRequest)},
        {10, -1, -1, sizeof(::murim::LeaveDungeonRequest)},
        {18, -1, -1, sizeof(::murim::DungeonActionRequest)},
        {28, 38, -1, sizeof(::murim::EnterDungeonResponse)},
        {40, -1, -1, sizeof(::murim::DungeonStatusNotification)},
        {50, -1, -1, sizeof(::murim::DungeonReward)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::murim::_EnterDungeonRequest_default_instance_._instance,
    &::murim::_LeaveDungeonRequest_default_instance_._instance,
    &::murim::_DungeonActionRequest_default_instance_._instance,
    &::murim::_EnterDungeonResponse_default_instance_._instance,
    &::murim::_DungeonStatusNotification_default_instance_._instance,
    &::murim::_DungeonReward_default_instance_._instance,
};
const char descriptor_table_protodef_dungeon_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\rdungeon.proto\022\005murim\032\014common.proto\"=\n\023"
    "EnterDungeonRequest\022\022\n\ndungeon_id\030\001 \001(\r\022"
    "\022\n\ndifficulty\030\002 \001(\r\"\025\n\023LeaveDungeonReque"
    "st\":\n\024DungeonActionRequest\022\022\n\ndungeon_id"
    "\030\001 \001(\r\022\016\n\006action\030\002 \001(\t\"M\n\024EnterDungeonRe"
    "sponse\022!\n\010response\030\001 \001(\0132\017.murim.Respons"
    "e\022\022\n\ndungeon_id\030\002 \001(\r\"U\n\031DungeonStatusNo"
    "tification\022\022\n\ndungeon_id\030\001 \001(\r\022$\n\006status"
    "\030\002 \001(\0162\024.murim.DungeonStatus\"J\n\rDungeonR"
    "eward\022\017\n\007item_id\030\001 \001(\r\022\r\n\005count\030\002 \001(\r\022\013\n"
    "\003exp\030\003 \001(\r\022\014\n\004gold\030\004 \001(\r*8\n\013DungeonType\022"
    "\n\n\006SINGLE\020\000\022\010\n\004TEAM\020\001\022\010\n\004RAID\020\002\022\t\n\005ARENA"
    "\020\003*_\n\021DungeonDifficulty\022\020\n\014DUNGEON_EASY\020"
    "\000\022\022\n\016DUNGEON_NORMAL\020\001\022\020\n\014DUNGEON_HARD\020\002\022"
    "\022\n\016DUNGEON_EXPERT\020\003*l\n\rDungeonStatus\022\027\n\023"
    "DUNGEON_NOT_STARTED\020\000\022\027\n\023DUNGEON_IN_PROG"
    "RESS\020\001\022\025\n\021DUNGEON_COMPLETED\020\002\022\022\n\016DUNGEON"
    "_FAILED\020\003b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_dungeon_2eproto_deps[1] =
    {
        &::descriptor_table_common_2eproto,
};
static ::absl::once_flag descriptor_table_dungeon_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_dungeon_2eproto = {
    false,
    false,
    697,
    descriptor_table_protodef_dungeon_2eproto,
    "dungeon.proto",
    &descriptor_table_dungeon_2eproto_once,
    descriptor_table_dungeon_2eproto_deps,
    1,
    6,
    schemas,
    file_default_instances,
    TableStruct_dungeon_2eproto::offsets,
    file_level_enum_descriptors_dungeon_2eproto,
    file_level_service_descriptors_dungeon_2eproto,
};
namespace murim {
const ::google::protobuf::EnumDescriptor* DungeonType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_dungeon_2eproto);
  return file_level_enum_descriptors_dungeon_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t DungeonType_internal_data_[] = {
    262144u, 0u, };
bool DungeonType_IsValid(int value) {
  return 0 <= value && value <= 3;
}
const ::google::protobuf::EnumDescriptor* DungeonDifficulty_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_dungeon_2eproto);
  return file_level_enum_descriptors_dungeon_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t DungeonDifficulty_internal_data_[] = {
    262144u, 0u, };
bool DungeonDifficulty_IsValid(int value) {
  return 0 <= value && value <= 3;
}
const ::google::protobuf::EnumDescriptor* DungeonStatus_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_dungeon_2eproto);
  return file_level_enum_descriptors_dungeon_2eproto[2];
}
PROTOBUF_CONSTINIT const uint32_t DungeonStatus_internal_data_[] = {
    262144u, 0u, };
bool DungeonStatus_IsValid(int value) {
  return 0 <= value && value <= 3;
}
// ===================================================================

class EnterDungeonRequest::_Internal {
 public:
};

EnterDungeonRequest::EnterDungeonRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:murim.EnterDungeonRequest)
}
EnterDungeonRequest::EnterDungeonRequest(
    ::google::protobuf::Arena* arena, const EnterDungeonRequest& from)
    : EnterDungeonRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE EnterDungeonRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void EnterDungeonRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, dungeon_id_),
           0,
           offsetof(Impl_, difficulty_) -
               offsetof(Impl_, dungeon_id_) +
               sizeof(Impl_::difficulty_));
}
EnterDungeonRequest::~EnterDungeonRequest() {
  // @@protoc_insertion_point(destructor:murim.EnterDungeonRequest)
  SharedDtor(*this);
}
inline void EnterDungeonRequest::SharedDtor(MessageLite& self) {
  EnterDungeonRequest& this_ = static_cast<EnterDungeonRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* EnterDungeonRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) EnterDungeonRequest(arena);
}
constexpr auto EnterDungeonRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(EnterDungeonRequest),
                                            alignof(EnterDungeonRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull EnterDungeonRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_EnterDungeonRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &EnterDungeonRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<EnterDungeonRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &EnterDungeonRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<EnterDungeonRequest>(), &EnterDungeonRequest::ByteSizeLong,
            &EnterDungeonRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(EnterDungeonRequest, _impl_._cached_size_),
        false,
    },
    &EnterDungeonRequest::kDescriptorMethods,
    &descriptor_table_dungeon_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* EnterDungeonRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> EnterDungeonRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::murim::EnterDungeonRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint32 difficulty = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(EnterDungeonRequest, _impl_.difficulty_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(EnterDungeonRequest, _impl_.difficulty_)}},
    // uint32 dungeon_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(EnterDungeonRequest, _impl_.dungeon_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(EnterDungeonRequest, _impl_.dungeon_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 dungeon_id = 1;
    {PROTOBUF_FIELD_OFFSET(EnterDungeonRequest, _impl_.dungeon_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 difficulty = 2;
    {PROTOBUF_FIELD_OFFSET(EnterDungeonRequest, _impl_.difficulty_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void EnterDungeonRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:murim.EnterDungeonRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.dungeon_id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.difficulty_) -
      reinterpret_cast<char*>(&_impl_.dungeon_id_)) + sizeof(_impl_.difficulty_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* EnterDungeonRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const EnterDungeonRequest& this_ = static_cast<const EnterDungeonRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* EnterDungeonRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const EnterDungeonRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:murim.EnterDungeonRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint32 dungeon_id = 1;
          if (this_._internal_dungeon_id() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                1, this_._internal_dungeon_id(), target);
          }

          // uint32 difficulty = 2;
          if (this_._internal_difficulty() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                2, this_._internal_difficulty(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:murim.EnterDungeonRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t EnterDungeonRequest::ByteSizeLong(const MessageLite& base) {
          const EnterDungeonRequest& this_ = static_cast<const EnterDungeonRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t EnterDungeonRequest::ByteSizeLong() const {
          const EnterDungeonRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:murim.EnterDungeonRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // uint32 dungeon_id = 1;
            if (this_._internal_dungeon_id() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_dungeon_id());
            }
            // uint32 difficulty = 2;
            if (this_._internal_difficulty() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_difficulty());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void EnterDungeonRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<EnterDungeonRequest*>(&to_msg);
  auto& from = static_cast<const EnterDungeonRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:murim.EnterDungeonRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_dungeon_id() != 0) {
    _this->_impl_.dungeon_id_ = from._impl_.dungeon_id_;
  }
  if (from._internal_difficulty() != 0) {
    _this->_impl_.difficulty_ = from._impl_.difficulty_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void EnterDungeonRequest::CopyFrom(const EnterDungeonRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:murim.EnterDungeonRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void EnterDungeonRequest::InternalSwap(EnterDungeonRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(EnterDungeonRequest, _impl_.difficulty_)
      + sizeof(EnterDungeonRequest::_impl_.difficulty_)
      - PROTOBUF_FIELD_OFFSET(EnterDungeonRequest, _impl_.dungeon_id_)>(
          reinterpret_cast<char*>(&_impl_.dungeon_id_),
          reinterpret_cast<char*>(&other->_impl_.dungeon_id_));
}

::google::protobuf::Metadata EnterDungeonRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class LeaveDungeonRequest::_Internal {
 public:
};

LeaveDungeonRequest::LeaveDungeonRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:murim.LeaveDungeonRequest)
}
LeaveDungeonRequest::LeaveDungeonRequest(
    ::google::protobuf::Arena* arena,
    const LeaveDungeonRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  LeaveDungeonRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:murim.LeaveDungeonRequest)
}

inline void* LeaveDungeonRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) LeaveDungeonRequest(arena);
}
constexpr auto LeaveDungeonRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(LeaveDungeonRequest),
                                            alignof(LeaveDungeonRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull LeaveDungeonRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_LeaveDungeonRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &LeaveDungeonRequest::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<LeaveDungeonRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &LeaveDungeonRequest::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<LeaveDungeonRequest>(), &LeaveDungeonRequest::ByteSizeLong,
            &LeaveDungeonRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(LeaveDungeonRequest, _impl_._cached_size_),
        false,
    },
    &LeaveDungeonRequest::kDescriptorMethods,
    &descriptor_table_dungeon_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* LeaveDungeonRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> LeaveDungeonRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::murim::LeaveDungeonRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata LeaveDungeonRequest::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class DungeonActionRequest::_Internal {
 public:
};

DungeonActionRequest::DungeonActionRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:murim.DungeonActionRequest)
}
inline PROTOBUF_NDEBUG_INLINE DungeonActionRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::murim::DungeonActionRequest& from_msg)
      : action_(arena, from.action_),
        _cached_size_{0} {}

DungeonActionRequest::DungeonActionRequest(
    ::google::protobuf::Arena* arena,
    const DungeonActionRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  DungeonActionRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.dungeon_id_ = from._impl_.dungeon_id_;

  // @@protoc_insertion_point(copy_constructor:murim.DungeonActionRequest)
}
inline PROTOBUF_NDEBUG_INLINE DungeonActionRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : action_(arena),
        _cached_size_{0} {}

inline void DungeonActionRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.dungeon_id_ = {};
}
DungeonActionRequest::~DungeonActionRequest() {
  // @@protoc_insertion_point(destructor:murim.DungeonActionRequest)
  SharedDtor(*this);
}
inline void DungeonActionRequest::SharedDtor(MessageLite& self) {
  DungeonActionRequest& this_ = static_cast<DungeonActionRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.action_.Destroy();
  this_._impl_.~Impl_();
}

inline void* DungeonActionRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) DungeonActionRequest(arena);
}
constexpr auto DungeonActionRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(DungeonActionRequest),
                                            alignof(DungeonActionRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull DungeonActionRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_DungeonActionRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &DungeonActionRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<DungeonActionRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &DungeonActionRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<DungeonActionRequest>(), &DungeonActionRequest::ByteSizeLong,
            &DungeonActionRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(DungeonActionRequest, _impl_._cached_size_),
        false,
    },
    &DungeonActionRequest::kDescriptorMethods,
    &descriptor_table_dungeon_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* DungeonActionRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 41, 2> DungeonActionRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::murim::DungeonActionRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string action = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(DungeonActionRequest, _impl_.action_)}},
    // uint32 dungeon_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DungeonActionRequest, _impl_.dungeon_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(DungeonActionRequest, _impl_.dungeon_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 dungeon_id = 1;
    {PROTOBUF_FIELD_OFFSET(DungeonActionRequest, _impl_.dungeon_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // string action = 2;
    {PROTOBUF_FIELD_OFFSET(DungeonActionRequest, _impl_.action_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\32\0\6\0\0\0\0\0"
    "murim.DungeonActionRequest"
    "action"
  }},
};

PROTOBUF_NOINLINE void DungeonActionRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:murim.DungeonActionRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.action_.ClearToEmpty();
  _impl_.dungeon_id_ = 0u;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* DungeonActionRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const DungeonActionRequest& this_ = static_cast<const DungeonActionRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* DungeonActionRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const DungeonActionRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:murim.DungeonActionRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint32 dungeon_id = 1;
          if (this_._internal_dungeon_id() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                1, this_._internal_dungeon_id(), target);
          }

          // string action = 2;
          if (!this_._internal_action().empty()) {
            const std::string& _s = this_._internal_action();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "murim.DungeonActionRequest.action");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:murim.DungeonActionRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t DungeonActionRequest::ByteSizeLong(const MessageLite& base) {
          const DungeonActionRequest& this_ = static_cast<const DungeonActionRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t DungeonActionRequest::ByteSizeLong() const {
          const DungeonActionRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:murim.DungeonActionRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string action = 2;
            if (!this_._internal_action().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_action());
            }
            // uint32 dungeon_id = 1;
            if (this_._internal_dungeon_id() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_dungeon_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void DungeonActionRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<DungeonActionRequest*>(&to_msg);
  auto& from = static_cast<const DungeonActionRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:murim.DungeonActionRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_action().empty()) {
    _this->_internal_set_action(from._internal_action());
  }
  if (from._internal_dungeon_id() != 0) {
    _this->_impl_.dungeon_id_ = from._impl_.dungeon_id_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DungeonActionRequest::CopyFrom(const DungeonActionRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:murim.DungeonActionRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DungeonActionRequest::InternalSwap(DungeonActionRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.action_, &other->_impl_.action_, arena);
        swap(_impl_.dungeon_id_, other->_impl_.dungeon_id_);
}

::google::protobuf::Metadata DungeonActionRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class EnterDungeonResponse::_Internal {
 public:
  using HasBits =
      decltype(std::declval<EnterDungeonResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(EnterDungeonResponse, _impl_._has_bits_);
};

void EnterDungeonResponse::clear_response() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.response_ != nullptr) _impl_.response_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
EnterDungeonResponse::EnterDungeonResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:murim.EnterDungeonResponse)
}
inline PROTOBUF_NDEBUG_INLINE EnterDungeonResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::murim::EnterDungeonResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

EnterDungeonResponse::EnterDungeonResponse(
    ::google::protobuf::Arena* arena,
    const EnterDungeonResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  EnterDungeonResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.response_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::murim::Response>(
                              arena, *from._impl_.response_)
                        : nullptr;
  _impl_.dungeon_id_ = from._impl_.dungeon_id_;

  // @@protoc_insertion_point(copy_constructor:murim.EnterDungeonResponse)
}
inline PROTOBUF_NDEBUG_INLINE EnterDungeonResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void EnterDungeonResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, response_),
           0,
           offsetof(Impl_, dungeon_id_) -
               offsetof(Impl_, response_) +
               sizeof(Impl_::dungeon_id_));
}
EnterDungeonResponse::~EnterDungeonResponse() {
  // @@protoc_insertion_point(destructor:murim.EnterDungeonResponse)
  SharedDtor(*this);
}
inline void EnterDungeonResponse::SharedDtor(MessageLite& self) {
  EnterDungeonResponse& this_ = static_cast<EnterDungeonResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.response_;
  this_._impl_.~Impl_();
}

inline void* EnterDungeonResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) EnterDungeonResponse(arena);
}
constexpr auto EnterDungeonResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(EnterDungeonResponse),
                                            alignof(EnterDungeonResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull EnterDungeonResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_EnterDungeonResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &EnterDungeonResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<EnterDungeonResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &EnterDungeonResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<EnterDungeonResponse>(), &EnterDungeonResponse::ByteSizeLong,
            &EnterDungeonResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(EnterDungeonResponse, _impl_._cached_size_),
        false,
    },
    &EnterDungeonResponse::kDescriptorMethods,
    &descriptor_table_dungeon_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* EnterDungeonResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> EnterDungeonResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(EnterDungeonResponse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::murim::EnterDungeonResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint32 dungeon_id = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(EnterDungeonResponse, _impl_.dungeon_id_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(EnterDungeonResponse, _impl_.dungeon_id_)}},
    // .murim.Response response = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(EnterDungeonResponse, _impl_.response_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .murim.Response response = 1;
    {PROTOBUF_FIELD_OFFSET(EnterDungeonResponse, _impl_.response_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // uint32 dungeon_id = 2;
    {PROTOBUF_FIELD_OFFSET(EnterDungeonResponse, _impl_.dungeon_id_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }}, {{
    {::_pbi::TcParser::GetTable<::murim::Response>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void EnterDungeonResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:murim.EnterDungeonResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.response_ != nullptr);
    _impl_.response_->Clear();
  }
  _impl_.dungeon_id_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* EnterDungeonResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const EnterDungeonResponse& this_ = static_cast<const EnterDungeonResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* EnterDungeonResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const EnterDungeonResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:murim.EnterDungeonResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .murim.Response response = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.response_, this_._impl_.response_->GetCachedSize(), target,
                stream);
          }

          // uint32 dungeon_id = 2;
          if (this_._internal_dungeon_id() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                2, this_._internal_dungeon_id(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:murim.EnterDungeonResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t EnterDungeonResponse::ByteSizeLong(const MessageLite& base) {
          const EnterDungeonResponse& this_ = static_cast<const EnterDungeonResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t EnterDungeonResponse::ByteSizeLong() const {
          const EnterDungeonResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:murim.EnterDungeonResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // .murim.Response response = 1;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.response_);
            }
          }
           {
            // uint32 dungeon_id = 2;
            if (this_._internal_dungeon_id() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_dungeon_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void EnterDungeonResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<EnterDungeonResponse*>(&to_msg);
  auto& from = static_cast<const EnterDungeonResponse&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:murim.EnterDungeonResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.response_ != nullptr);
    if (_this->_impl_.response_ == nullptr) {
      _this->_impl_.response_ =
          ::google::protobuf::Message::CopyConstruct<::murim::Response>(arena, *from._impl_.response_);
    } else {
      _this->_impl_.response_->MergeFrom(*from._impl_.response_);
    }
  }
  if (from._internal_dungeon_id() != 0) {
    _this->_impl_.dungeon_id_ = from._impl_.dungeon_id_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void EnterDungeonResponse::CopyFrom(const EnterDungeonResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:murim.EnterDungeonResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void EnterDungeonResponse::InternalSwap(EnterDungeonResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(EnterDungeonResponse, _impl_.dungeon_id_)
      + sizeof(EnterDungeonResponse::_impl_.dungeon_id_)
      - PROTOBUF_FIELD_OFFSET(EnterDungeonResponse, _impl_.response_)>(
          reinterpret_cast<char*>(&_impl_.response_),
          reinterpret_cast<char*>(&other->_impl_.response_));
}

::google::protobuf::Metadata EnterDungeonResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class DungeonStatusNotification::_Internal {
 public:
};

DungeonStatusNotification::DungeonStatusNotification(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:murim.DungeonStatusNotification)
}
DungeonStatusNotification::DungeonStatusNotification(
    ::google::protobuf::Arena* arena, const DungeonStatusNotification& from)
    : DungeonStatusNotification(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE DungeonStatusNotification::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void DungeonStatusNotification::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, dungeon_id_),
           0,
           offsetof(Impl_, status_) -
               offsetof(Impl_, dungeon_id_) +
               sizeof(Impl_::status_));
}
DungeonStatusNotification::~DungeonStatusNotification() {
  // @@protoc_insertion_point(destructor:murim.DungeonStatusNotification)
  SharedDtor(*this);
}
inline void DungeonStatusNotification::SharedDtor(MessageLite& self) {
  DungeonStatusNotification& this_ = static_cast<DungeonStatusNotification&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* DungeonStatusNotification::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) DungeonStatusNotification(arena);
}
constexpr auto DungeonStatusNotification::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(DungeonStatusNotification),
                                            alignof(DungeonStatusNotification));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull DungeonStatusNotification::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_DungeonStatusNotification_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &DungeonStatusNotification::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<DungeonStatusNotification>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &DungeonStatusNotification::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<DungeonStatusNotification>(), &DungeonStatusNotification::ByteSizeLong,
            &DungeonStatusNotification::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(DungeonStatusNotification, _impl_._cached_size_),
        false,
    },
    &DungeonStatusNotification::kDescriptorMethods,
    &descriptor_table_dungeon_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* DungeonStatusNotification::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> DungeonStatusNotification::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::murim::DungeonStatusNotification>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .murim.DungeonStatus status = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DungeonStatusNotification, _impl_.status_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(DungeonStatusNotification, _impl_.status_)}},
    // uint32 dungeon_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DungeonStatusNotification, _impl_.dungeon_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(DungeonStatusNotification, _impl_.dungeon_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 dungeon_id = 1;
    {PROTOBUF_FIELD_OFFSET(DungeonStatusNotification, _impl_.dungeon_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // .murim.DungeonStatus status = 2;
    {PROTOBUF_FIELD_OFFSET(DungeonStatusNotification, _impl_.status_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void DungeonStatusNotification::Clear() {
// @@protoc_insertion_point(message_clear_start:murim.DungeonStatusNotification)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.dungeon_id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.status_) -
      reinterpret_cast<char*>(&_impl_.dungeon_id_)) + sizeof(_impl_.status_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* DungeonStatusNotification::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const DungeonStatusNotification& this_ = static_cast<const DungeonStatusNotification&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* DungeonStatusNotification::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const DungeonStatusNotification& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:murim.DungeonStatusNotification)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint32 dungeon_id = 1;
          if (this_._internal_dungeon_id() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                1, this_._internal_dungeon_id(), target);
          }

          // .murim.DungeonStatus status = 2;
          if (this_._internal_status() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                2, this_._internal_status(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:murim.DungeonStatusNotification)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t DungeonStatusNotification::ByteSizeLong(const MessageLite& base) {
          const DungeonStatusNotification& this_ = static_cast<const DungeonStatusNotification&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t DungeonStatusNotification::ByteSizeLong() const {
          const DungeonStatusNotification& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:murim.DungeonStatusNotification)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // uint32 dungeon_id = 1;
            if (this_._internal_dungeon_id() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_dungeon_id());
            }
            // .murim.DungeonStatus status = 2;
            if (this_._internal_status() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_status());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void DungeonStatusNotification::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<DungeonStatusNotification*>(&to_msg);
  auto& from = static_cast<const DungeonStatusNotification&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:murim.DungeonStatusNotification)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_dungeon_id() != 0) {
    _this->_impl_.dungeon_id_ = from._impl_.dungeon_id_;
  }
  if (from._internal_status() != 0) {
    _this->_impl_.status_ = from._impl_.status_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DungeonStatusNotification::CopyFrom(const DungeonStatusNotification& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:murim.DungeonStatusNotification)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DungeonStatusNotification::InternalSwap(DungeonStatusNotification* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DungeonStatusNotification, _impl_.status_)
      + sizeof(DungeonStatusNotification::_impl_.status_)
      - PROTOBUF_FIELD_OFFSET(DungeonStatusNotification, _impl_.dungeon_id_)>(
          reinterpret_cast<char*>(&_impl_.dungeon_id_),
          reinterpret_cast<char*>(&other->_impl_.dungeon_id_));
}

::google::protobuf::Metadata DungeonStatusNotification::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class DungeonReward::_Internal {
 public:
};

DungeonReward::DungeonReward(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:murim.DungeonReward)
}
DungeonReward::DungeonReward(
    ::google::protobuf::Arena* arena, const DungeonReward& from)
    : DungeonReward(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE DungeonReward::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void DungeonReward::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, item_id_),
           0,
           offsetof(Impl_, gold_) -
               offsetof(Impl_, item_id_) +
               sizeof(Impl_::gold_));
}
DungeonReward::~DungeonReward() {
  // @@protoc_insertion_point(destructor:murim.DungeonReward)
  SharedDtor(*this);
}
inline void DungeonReward::SharedDtor(MessageLite& self) {
  DungeonReward& this_ = static_cast<DungeonReward&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* DungeonReward::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) DungeonReward(arena);
}
constexpr auto DungeonReward::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(DungeonReward),
                                            alignof(DungeonReward));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull DungeonReward::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_DungeonReward_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &DungeonReward::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<DungeonReward>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &DungeonReward::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<DungeonReward>(), &DungeonReward::ByteSizeLong,
            &DungeonReward::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(DungeonReward, _impl_._cached_size_),
        false,
    },
    &DungeonReward::kDescriptorMethods,
    &descriptor_table_dungeon_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* DungeonReward::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2> DungeonReward::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::murim::DungeonReward>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint32 gold = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DungeonReward, _impl_.gold_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(DungeonReward, _impl_.gold_)}},
    // uint32 item_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DungeonReward, _impl_.item_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(DungeonReward, _impl_.item_id_)}},
    // uint32 count = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DungeonReward, _impl_.count_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(DungeonReward, _impl_.count_)}},
    // uint32 exp = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DungeonReward, _impl_.exp_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(DungeonReward, _impl_.exp_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 item_id = 1;
    {PROTOBUF_FIELD_OFFSET(DungeonReward, _impl_.item_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 count = 2;
    {PROTOBUF_FIELD_OFFSET(DungeonReward, _impl_.count_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 exp = 3;
    {PROTOBUF_FIELD_OFFSET(DungeonReward, _impl_.exp_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 gold = 4;
    {PROTOBUF_FIELD_OFFSET(DungeonReward, _impl_.gold_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void DungeonReward::Clear() {
// @@protoc_insertion_point(message_clear_start:murim.DungeonReward)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.item_id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.gold_) -
      reinterpret_cast<char*>(&_impl_.item_id_)) + sizeof(_impl_.gold_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* DungeonReward::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const DungeonReward& this_ = static_cast<const DungeonReward&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* DungeonReward::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const DungeonReward& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:murim.DungeonReward)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint32 item_id = 1;
          if (this_._internal_item_id() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                1, this_._internal_item_id(), target);
          }

          // uint32 count = 2;
          if (this_._internal_count() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                2, this_._internal_count(), target);
          }

          // uint32 exp = 3;
          if (this_._internal_exp() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                3, this_._internal_exp(), target);
          }

          // uint32 gold = 4;
          if (this_._internal_gold() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                4, this_._internal_gold(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:murim.DungeonReward)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t DungeonReward::ByteSizeLong(const MessageLite& base) {
          const DungeonReward& this_ = static_cast<const DungeonReward&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t DungeonReward::ByteSizeLong() const {
          const DungeonReward& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:murim.DungeonReward)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // uint32 item_id = 1;
            if (this_._internal_item_id() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_item_id());
            }
            // uint32 count = 2;
            if (this_._internal_count() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_count());
            }
            // uint32 exp = 3;
            if (this_._internal_exp() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_exp());
            }
            // uint32 gold = 4;
            if (this_._internal_gold() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_gold());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void DungeonReward::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<DungeonReward*>(&to_msg);
  auto& from = static_cast<const DungeonReward&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:murim.DungeonReward)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_item_id() != 0) {
    _this->_impl_.item_id_ = from._impl_.item_id_;
  }
  if (from._internal_count() != 0) {
    _this->_impl_.count_ = from._impl_.count_;
  }
  if (from._internal_exp() != 0) {
    _this->_impl_.exp_ = from._impl_.exp_;
  }
  if (from._internal_gold() != 0) {
    _this->_impl_.gold_ = from._impl_.gold_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DungeonReward::CopyFrom(const DungeonReward& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:murim.DungeonReward)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DungeonReward::InternalSwap(DungeonReward* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DungeonReward, _impl_.gold_)
      + sizeof(DungeonReward::_impl_.gold_)
      - PROTOBUF_FIELD_OFFSET(DungeonReward, _impl_.item_id_)>(
          reinterpret_cast<char*>(&_impl_.item_id_),
          reinterpret_cast<char*>(&other->_impl_.item_id_));
}

::google::protobuf::Metadata DungeonReward::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace murim
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_dungeon_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
